name: cycles
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.*
  - cmake
  - make
  - clangxx
  - doxygen
  - spdlog==1.14.*
  - sfml==2.6.*
  - pip 
  - pip:
    - breathe==4.35.0
    - sphinx==7.4.7
    - sphinx_rtd_theme==2.0.0
